apiVersion: v1
kind: Pod
metadata:
  name: mock-server-app
  labels:
    test: mock-server-app
spec:
  containers:
  - name: mock-server-nodejs
    image: wimbervoets/mock-server-nodejs:1.0
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        port: 8080
        path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        port: 8080
        path: /health
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 2
